language: php
php:
- 5.3
- 5.4
- 5.5
env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.0 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=1
  - WP_VERSION=3.9 WP_MULTISITE=0
  - WP_VERSION=3.9 WP_MULTISITE=1
  - WP_VERSION=3.8 WP_MULTISITE=0
  - WP_VERSION=3.8 WP_MULTISITE=1
  global:
    secure: SMPml9xPNS2AGYZyRzGU83qdH85tBI4VB4mTtRISE1DB64Tjg9WcD1Zrztw2BlynARgHNZD/BzVDVhQvIjzhRWvqPGTGw22RgikaZJV+eCBMaZ4VIP9uSdsgCWRpFkPdJbnVARfS9eWEehaacVOVM0CKRN8G3GQYWLVE5+m1LIw=
sudo: false
install:
- git config --global user.email "paul@hmn.md"
- git config --global user.name "Paul de Wouters"
notifications:
  email: false
  hipchat:
    rooms:
      secure: DdRbiWiLDnyzgRCFUjo+wiWCR6iNLTlipdLRCWufdeHPgpgAvAbo2+7D9Uvh+tjK5smynGTQfmDAnh4q7+Jy6qLOse7k/YBIvgLINEyCQ9EenpJYfz9C7/fAEvvRJpT6LObw68y6T35qsRMyFv0eeNemEuwDcMc0oEXeRLCgegQ=
before_script:
- composer selfupdate --quiet
- composer install -n --prefer-dist --no-progress
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- mkdir -p $TRAVIS_BUILD_DIR/build/docs
script:
- phpunit --testsuite backup --coverage-clover=coverage.clover
- phpunit --testsuite schedule --coverage-clover=coverage.clover
- phpunit --testsuite other --coverage-clover=coverage.clover

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover