language: php
sudo: false
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

env:
  # trunk:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  # latest stable:
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=1
  # previous stable:
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=1
  # earliest supported:
  - WP_VERSION=3.9 WP_MULTISITE=0
  - WP_VERSION=3.9 WP_MULTISITE=1

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true
  exclude:
    # don't test 3.9 on hiphop:
    - php: hhvm
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=3.9 WP_MULTISITE=1

before_install:
  # set up WP install
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - mkdir -p $WP_DEVELOP_DIR
  - git clone --depth=1 git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
  # set up tests config
  - cd $WP_DEVELOP_DIR
  - echo $WP_DEVELOP_DIR
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
  - sed -i "s/yourusernamehere/root/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php
  # set up database
  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot

install:
  - git config --global user.email "paul@hmn.md"
  - git config --global user.name "Paul de Wouters"
notifications:
  email: false
  slack:
    secure: ZyXhKGpR/VtggG3vcCaZ+50HBn4STi2fOvMKrmZaeS44s+j6lhkYt7qT1UeU1o2Vox2WCrdqfZqT370f4OV3izAgf7Ln+vIYxZvCywL2Cyt4YbHVPX0pMwuDuAW6a1zG5oP87CFZh9YYCHQ6HfX9ATKtnqiuMFx/SjOcD1Yb4Lk=
script:
  - phpunit --testsuite backup --coverage-clover=coverage.clover
  - phpunit --testsuite schedule --coverage-clover=coverage.clover
  - phpunit --testsuite other --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
