language: php
php:
- 5.3
- 5.4
- 5.5
env:
  global:
  - secure: gRaJVjznkdJlPA/PCR/dj8Z8ejtLebuSbZay++OOuCE4JLDIJnGMQCNd91W1ljxtqnS2ThCmC1VhbE/AJ1OmQ9U5UVgUX45UCAEaH2VcuvUjM/Khho7rW9wb+Gke+i+dZ1HdW76Xb4w2N/8WlEQsldFTwMrB4K1mOYBCc5Vbl8I=
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.0 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=1
  - WP_VERSION=3.9 WP_MULTISITE=0
  - WP_VERSION=3.9 WP_MULTISITE=1
  - WP_VERSION=3.8 WP_MULTISITE=0
  - WP_VERSION=3.8 WP_MULTISITE=1
sudo: false
notifications:
  email: false
  hipchat:
    rooms:
      secure: DdRbiWiLDnyzgRCFUjo+wiWCR6iNLTlipdLRCWufdeHPgpgAvAbo2+7D9Uvh+tjK5smynGTQfmDAnh4q7+Jy6qLOse7k/YBIvgLINEyCQ9EenpJYfz9C7/fAEvvRJpT6LObw68y6T35qsRMyFv0eeNemEuwDcMc0oEXeRLCgegQ=
before_script:
- composer selfupdate --quiet
- composer install -n --prefer-source --dev
- export WP_TESTS_DIR=/tmp/wordpress-tests-lib/
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- mkdir -p build/docs
script:
- phpunit --coverage-clover=coverage.clover
- php vendor/bin/phpdoc -d $TRAVIS_BUILD_DIR -t $TRAVIS_BUILD_DIR/build/docs --ignore
  $TRAVIS_BUILD_DIR/vendor/,$TRAVIS_BUILD_DIR/build/,$TRAVIS_BUILD_DIR/hm-backup/,$TRAVIS_BUILD_DIR/backdrop/,$TRAVIS_BUILD_DIR/assets/,$TRAVIS_BUILD_DIR/bin/,$TRAVIS_BUILD_DIR/languages/,$TRAVIS_BUILD_DIR/node_modules/,$TRAVIS_BUILD_DIR/tests/,$TRAVIS_BUILD_DIR/readme/
after_script:
- $TRAVIS_BUILD_DIR/bin/travis_shell_after_success.sh
